version: "3"

services:
  monerod:
    container_name: monerod
    build:
      context: .
    volumes:
      - ./monerod.conf:/home/monero/monerod.conf
      - ./volumes/bitmonero/:/home/monero/.bitmonero
      - ./volumes/log:/home/monero/log
    ports:
      - 18080:18080
      - 18081:18081
      - 18089:18089
